### ISSUE TITLE
Strange build failure when building PR

### ISSUE THREAD

**Issue by AntStephenson** [kiegroup/kie-build-helper-jenkins-plugin#18]
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions-pullrequests/891/

**Comment by AntStephenson** [comment]
Another failure, could be related ; https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-pullrequests/1675/console

**Comment by mareknovotny** [comment]
Copying here the exception stacktrace as links to jobs can be garbage collected on jenkins.
```
Using repository-list.txt from GitHubRepository{owner='kiegroup', name='droolsjbpm-build-bootstrap'},GitBranch{name='master'}.
Unexpected error while executing the Upstream repositories builder for PR builds! null
java.lang.NullPointerException
	at org.kie.jenkinsci.plugins.kieprbuildshelper.GitHubUtils.findOpenPullRequest(GitHubUtils.java:62)
	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.transformToRefSpecs(AbstractPRBuilder.java:146)
	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:122)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

It seems that line is producing NPE at some cases
```
pr.getHead().getRepository().getOwner().getLogin().equals(prAuthor)) {
```

We should split the conditition expression to see what is really the root cause.
