### ISSUE TITLE
NPE in GitHubPRSummary.fromPRLink

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-build-helper-jenkins-plugin#3]
```
Unexpected error while executing the DownstreamReposBuilder! null
12:08:23 java.lang.NullPointerException
12:08:23 	at org.kie.jenkinsci.plugins.kieprbuildshelper.GitHubPRSummary.fromPRLink(GitHubPRSummary.java:89)
12:08:23 	at org.kie.jenkinsci.plugins.kieprbuildshelper.DownstreamReposBuilder.perform(DownstreamReposBuilder.java:121)
12:08:23 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:08:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
12:08:23 	at hudson.model.Build$BuildExecution.build(Build.java:205)
12:08:23 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
12:08:23 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
12:08:23 	at hudson.model.Run.execute(Run.java:1728)
12:08:23 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:08:23 	at hudson.model.ResourceController.execute(ResourceController.java:98)
12:08:23 	at hudson.model.Executor.run(Executor.java:404)
12:08:23 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
```

**Comment by psiroky** [comment]
Recently solved https://github.com/kiegroup/kie-build-helper-jenkins-plugin/commit/2f03b3c591fa2bcfc509f064a3e2d01b1cbcc52d.
